🌐 Complete Website Overhaul: Design, Responsiveness, and Content
IsaMarvin/Synthex pull request #1
Opened 2023-08-08 21:31 UTC by IsaMarvin

# Synthex Website Implementation: :rocket:

This pull request marks my inaugural implementation of the Synthex 2023 conference website. I've combined various elements to create a cohesive, visually appealing, and responsive online platform for the conference. 🎉

### Website Highlights:

- 🎨 **Fresh Design:** From hero sections to footers, the website now boasts enhanced alignment, spacing, and a harmonious color scheme. Users will be greeted by a polished layout that elevates their browsing experience.

- 👥 **Intuitive Navigation:** I've reimagined the navigation to be more user-friendly. With a responsive menu and a seamless mobile interface, users can easily access content from any device.

- 📸 **Dynamic Speaker Showcase:** The "Previous Events" section features dynamic speaker cards that adapt gracefully to different screen sizes. Users can explore speaker details seamlessly, ensuring an engaging experience.

- 👓 **Responsive Everywhere:** Every element, from header to footer, is designed to adapt effortlessly to various devices. The website guarantees a consistent user experience across platforms.

- 🎉 **Enriched Content:** Beyond design improvements, I've enriched the content of the "Synthex Emblem" and "Previous Events" sections. These additions provide captivating insights that strengthen user engagement with the Synthex brand and history.

- 📊 **Data Empowerment:** By utilizing JavaScript objects, I've presented data-driven content that delivers valuable insights to users.

- 🚀 **Easy Deployment:** The revamped website is now live on GitHub Pages, allowing global access to the new Synthex experience.

Deployed Website: [Check out the Synthex 2023 Website](https://isamarvin.github.io/Synthex/)

This pull request demonstrates the successful implementation of the Synthex website, aligning with the objectives of creating a visually captivating, functionally enriched, and user-centric digital platform. I eagerly anticipate feedback on this maiden endeavor! :sparkles:

2023-08-08 23:00 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @IsaMarvin , 

Good job so far!, very excellent work 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ All linters checks are ok
✅ The correct workflow is used. 
✅ Very descriptive Pull Request(PR)
✅ Your work is well documented.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-08 23:00 UTC, bobb-Rob commented on about.html
> +            <li><a href="about.html">About</a></li>
- [ ] Please add a href link to the Home page and update the text from -About to Home. Since we are already on the About page, it just makes sense to link back to the Home page.

2023-08-08 23:00 UTC, bobb-Rob commented on index.html
> +
You have done an excellent work. Well done 👏🏾 

- [ ] According to the original design by Cindy, on the mobile view of the Home page, we can see that the Partner section and footer are not visible. Kindly implement this.

- [ ] Also, on the mobile view of the About page the `partner section` should be visible but hidden from the Desktop view. You have correctly made the partner section hidden on the desktop view of the About page. Please make it visible on the mobile view.

Your project home page mobile view 👇🏾 

![image](https://github.com/IsaMarvin/Synthex/assets/84156714/58a2d562-b147-48d4-9526-5baec4024b39)

Original Design 👇🏾 
<img width="635" alt="image" src="https://github.com/IsaMarvin/Synthex/assets/84156714/24798e5a-a7f7-43ec-8fb7-9b9ce1ba4a2d">

2023-08-09 01:08 UTC, taldr27 approved these changes
# Status: Approved! 🟢 
Hi @IsaMarvin, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

## Highlights 🎉
✅ Professional and customized README. 
✅ Linters tests passing.
✅ Correct use of GitHub Flow.
✅ Great job with your mobile and desktop designs.
✅ Incorporates feedback from previous code reviews.
✅ Good job using media queries.

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-08-09 01:15 UTC, merged